### ISSUE TITLE
how to access keypoints data

### ISSUE THREAD

**Issue by saruzaru** [keijiro/BodyPixBarracuda#1]
sorry for the noob question, but I couldn't figure it out by myself. 
How can i read x and y properties for the nose, ears, etc?

**Comment by keijiro** [comment]
You can use `BodyPixRuntime.Keypoints`.

https://github.com/keijiro/BodyPixBarracuda/blob/main/Packages/jp.keijiro.bodypix/Script/BodyPixRuntime.cs#L26

At the moment, it's exposed as a compute buffer, so you only can access it from GPU.

I'm thinking of adding C# interface to it, like `Keypoint[] BodyPixRuntime.KeypointsAsArray`.

**Comment by saruzaru** [comment]
That's what I tried, but I couldn't figure out how to get the data from the Compute Buffer. 
I don't understand shaders much.

**Comment by keijiro** [comment]
I added a keypoint accessor property in the latest update. Please check the Keypoints.unity example for details.

**Comment by saruzaru** [comment]
Thank you!
