### ISSUE TITLE
mobile device support

### ISSUE THREAD

**Issue by yun-li** [keijiro/BodyPixBarracuda#5]
I tried to run it on a mobile device and it is very slow, is there a way to decrease computation requirement?

**Comment by keijiro** [comment]
Unfortunately, no, there is no easy way to decrease the computation load. I'd recommend using the lightest model (MobileNetV1-x050-stride16.onnx) and decreasing the input resolution.

**Comment by keijiro** [comment]
I'm closing this issue now. Please feel free to reopen it for further problems.
