### ISSUE TITLE
IOS Release build Example

### ISSUE THREAD

**Issue by zeedevio** [keijiro/BodyPixBarracuda#6]
Is this possible, I can not override barracuda and burst to not use the preview packages

**Comment by keijiro** [comment]
I think you can build it as release even if it contains preview packages.

**Comment by zeedevio** [comment]
Good day, I'm coming from a javascript background and only recently started working on unity. really like the information you shared, but struggling to get it to a point where I can test it completely. so my knowledge with unity is that preview packages prevent you from building a production release app, but that small fish for now. but apart from that can you help me pointers or share a package of the setup connecting ar foundation camera or. a script where I can at least see a log of output found in the live video feed.

**Comment by keijiro** [comment]
> preview packages prevent you from building a production release app

No. You can build an app as release with preview packages.

**Comment by keijiro** [comment]
I'm closing this issue as resolved. Please reopen it for further problem on the original post, or create a new issue for another topic.
